### ISSUE TITLE
aboot with hierfstat::fstat

### ISSUE THREAD

**Issue by willmatt** [grunwaldlab/poppr#111]
I've been trying to use aboot with hierfstat's fstat with little success.
Following are the commands I used from a clean environment:
```
install.packages("poppr")
install.packages("hierfstat")
library("poppr")
library("hierfstat")
data("nancycats")
my.fst.dist <- function(s) fstat(x = s,pop = NULL,fstonly = TRUE)
nancy_tree <- aboot(nancycats, distance = "my.fst.dist")
```
This gives the output:

> Error in fstat(s) : x is not a valid genind object 

However I also get the following:

`nancycats`

> /// GENIND OBJECT /////////
> 
>  // 237 individuals; 9 loci; 108 alleles; size: 145.3 Kb
> 
>  // Basic content
>    @tab:  237 x 108 matrix of allele counts
> ......

and

`fstat(nancycats)
`

gives

>              pop       Ind
> Total 0.08494959 0.1952946
> pop   0.00000000 0.1205890

Any help would be appreciated.
Thanks,
Will

**Comment by zkamvar** [comment]
Hi Will,

Sorry about the confusing error. This is an unfortunate side-effect of how `aboot()` works internally. It converts a genind or genpop object to a bootgen object. I will create a `bootgen2genind()` and `bootgetn2genpop()` method for conversion purposes and update the documentation for the next version.

Additionally, it looks like you want to obtain the relationship between the hierarchical levels and assess the internal consistency of the loci to the hierarchy. Unfortunately, the `fstat()` function wasn't really designed for that for several reasons. Here's a workaround using the `boot.phylo()` function from *ape* (Which `aboot()` uses internally):


```r
library("ape")
library("poppr")
library("hierfstat")
data("microbov")
mic <- genind2hierfstat(microbov)
csb  <- data.frame(other(microbov))[c(1, 3, 2)] # country and breed
my.fst.tree <- function(s, p){
  # The matrix comes in with the lower triangle filled with zeroes
  f <- varcomp.glob(levels = p, loci = s)$F
  tf <- t(f)        # we must transpose it
  df <- as.dist(tf) # and convert it to a dist object
  nj(df)
}
x <- my.fst.tree(as.matrix(mic[-1]), csb)
boot.phylo(x, mic[-1], FUN = function(i) my.fst.tree(i, csb), B = 2)
```

As you can see, there's a lot of pre-processing that makes this particular output difficult to deal with. 

Thanks for pointing this out. I hope this was helpful.

Zhian

**Comment by zkamvar** [comment]
I'm going to close this issue as I haven't heard anything on this for a while.
