### ISSUE TITLE
Scale MSN node size by area, not radius

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#154]
Currently, igraph uses radius to scale the pies in the graph. This makes for some large disparities in how one sample compares to eight samples. If we transform the number of MLGs by √(area/π), then we can also add an accurate scale for the node sizes.

Here's a display of the differences. White node show the current implementation for 1, 4, 8, and 16 individuals and grey nodes show the potential implementation (enlarged). 

``` r
a2r <- function(a) sqrt(a/pi)
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
x <- erdos.renyi.game(4, 0.1)
plot.igraph(x, 
            layout = layout_on_grid(x, 4), 
            vertex.shape = "pie", 
            vertex.pie = as.list(rep(1, 4)), 
            vertex.size = a2r(c(1, 4, 8, 16)*500), 
            vertex.pie.color = "grey50",
            vertex.label = NA)
plot.igraph(x, 
            layout = layout_on_grid(x, 4), 
            vertex.shape = "pie", 
            vertex.pie = as.list(rep(1, 4)), 
            vertex.size = c(1, 4, 8, 16)*3, 
            vertex.label = NA,
            add = TRUE)
```

![](https://i.imgur.com/IIDSe1W.png)

**Comment by grunwald** [comment]
Brilliant. Thanks for working on this.

**Comment by zkamvar** [comment]
Note:

There's no need to divide by π. If I just take the square root of n, then the smallest radius will be 1.
