### ISSUE TITLE
Problem with Allele frequency determination

### ISSUE THREAD

**Issue by Jvplanz** [grunwaldlab/poppr#155]
I have trying to find out how to do this!!  I have a set of STR data for 21 loci and 200 ind.  the dataset works fin and I can get summer stats and all.
I used the scripts from the package documentation:

# Get raw number of private alleles per locus.
(pal <- private_alleles(Pinf, locus ~ Country, count.alleles = FALSE))
# Get percentages.
sweep(pal, 2, nAll(Pinf)[colnames(pal)], FUN = "/")
#
Had to change the count.alleles=FALSE to TRUE
and it gave me a matrix with the allele counts for each allele at each locus correctly.

BUT...

The sweep command however does not give me anything useful...all fields read NA:
> sweep(athospal, 2, nAll(ATHOSPara)[colnames(athospal)], FUN = "/")
  HUMTPOX.8 HUMTPOX.11 HUMTPOX.10 HUMTPOX.9 HUMTPOX.12 HUMvWA.11 HUMvWA.16 HUMvWA.17 HUMvWA.18
1        NA         NA         NA        NA         NA        NA        NA        NA        NA
  HUMvWA.15 HUMvWA.14 HUMvWA.19 HUMvWA.21 D13S317.11 D13S317.12 D13S317.8 D13S317.10 D13S317.9
1        NA        NA        NA        NA         NA         NA        NA         NA        NA
  
How do I get the frequency proportions for the alleles?

Any assistance would be greatly Appreciated!!
John

**Comment by zkamvar** [comment]
Hello,

This message is a cross-post from the poppr forum: https://groups.google.com/d/msg/poppr/577jwbWlphw/T0W4ysMiAAAJ

Please do not cross-post. It makes it difficult to track the answers for people who search for this problem in the future.

I am currently at a workshop and will be able to answer on the forum when I return. Thank you for your patience.

Best,
Zhian

**Comment by Jvplanz** [comment]
Hi Zhian
Yes I did post this on the google group page…but was not sure that it actually loaded…there was no entry on the lit…so I tried the Git Hub
Appreciate any help you can give
Enjoy the workshop!
I look forward to hearing from you
Best regards
John


John V. Planz, Ph.D.
Associate Professor
Department of Molecular Cell Biology and Genetics
Graduate School of Biomedical Sciences
UNT Health Science Center
3500 Camp Bowie Blvd, CBH 360
Fort Worth, TX 76107
817-735-2397
