### ISSUE TITLE
issue by poppr

### ISSUE THREAD

**Issue by huangl07** [grunwaldlab/poppr#163]
dear all

I  have use your popr with several vcf file,when poppr werr used,it is very slow 

my script is poppr("pop.gtx")

thank you

**Comment by zkamvar** [comment]
Hi, 

This is similar to this post in the *poppr* forums:

https://groups.google.com/d/msg/poppr/t5sCsjfC4Ao/kEzRlAGsDgAJ

Please see my answer there.
