### ISSUE TITLE
'shufflepop' methods

### ISSUE THREAD

**Issue by dionnecargy** [grunwaldlab/poppr#192]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [X] I have the most recent version of poppr and R
 - [ ] I have found a bug
 - [X] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [X] I want to request a new feature
--------
Please include a brief description of the problem with a code example:

Hi, I've been trying to understand which method to use (1 to 4) for calculating the index of association over all loci (ia) and in a pairwise manner (pair.ia). The data I am looking at are for haploid individuals. I have found it difficult to understand the description under the 'shufflepop' function in R and was hoping for clarification. 

```r
ia(BD.N55, sample = 9999, method = 4, quiet = FALSE, plot = TRUE, hist = TRUE, index = "Ia", valuereturn = FALSE)
pair.ia(BD.N55, sample = 9999, quiet = FALSE, method = 1)

```

---------

**Comment by zkamvar** [comment]
The methods are detailed in the data import and manipulation manual: https://grunwaldlab.github.io/poppr/articles/poppr_manual.html#data-manip:shuffle

If you let me know what part of the documentation was difficult to understand, I'll do my best to clarify it here and in future poppr versions.

**Comment by zkamvar** [comment]
I'm going to close this issue for now. If you have anything you want to follow up on, just reply to this thread and I'll try to get back to you as soon as I can.
