### ISSUE TITLE
Issue when reading in GenAlEx csv

### ISSUE THREAD

**Issue by planteering** [grunwaldlab/poppr#214]
---------------------------------------------

 - [x] I have the most recent version of poppr and R
 - [x] I have found a bug
   - [x] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [x] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Hello,

I believe I've found a bug in the read.genalex function. When reading tables of SNPs for diploid individuals encoded with nucleotide characters, if a loci in the genalex input consists only of Ts in the second column, poppr reads in an allele called TRUE, instead of T. 
For example - If we have a loci in a GenAlEx-formatted .csv where the observed alleles are G/T and T/T, then poppr reports 3 alleles rather than two at the loci, G, T, and TRUE!

I've attached a tiny example dataset that illustrates the problem. I've made it very specific to the exact context in which I encountered this issue, hence the NAs. GitHub won't let me upload a .csv so I've uploaded as text file, but it's formated as a GenAlEx csv nonetheless.
[test.txt](https://github.com/grunwaldlab/poppr/files/4633600/test.txt)

This is my first time reporting a bug, I hope this information is sufficient!

Best,

Alex

```r
library(poppr)

testgene <- read.genalex("test.txt")
summary(testgene)
tab(testgene)
```

---------

**Comment by zkamvar** [comment]
That looks like a bug to me! Thank you for bringing it to my attention. I'll try to get it fixed and on CRAN soon!

Just to confirm, this is the behavior I got when I ran a reprex using your example file:

``` r
suppressPackageStartupMessages(library(poppr))
testgene <- read.genalex('https://github.com/grunwaldlab/poppr/files/4633600/test.txt')
tab(testgene)
#>     605-4471.T 605-4471.C 681-4471.G 681-4471.TRUE 681-4471.T 682-4471.G
#> A71          2          0          1             1          0          1
#> A72          0          2         NA            NA         NA         NA
#> A73          2          0          1             1          0          1
#> A74          2          0          1             1          0          1
#> A75          2          0          1             1          0          1
#> A76          2          0          0             1          1          0
#>     682-4471.TRUE 682-4471.T
#> A71             1          0
#> A72            NA         NA
#> A73             1          0
#> A74             1          0
#> A75             1          0
#> A76             1          1
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by planteering** [comment]
Yep, that's exactly the same as what I got!

**Comment by zkamvar** [comment]
Update: it's happening because `read.table()` likes to guess what the column type is and a column of all "T" or all "F" is assumed to be logical.
