### ISSUE TITLE
Bruvos Distance function comparing n individuals to a reference set. 

### ISSUE THREAD

**Issue by davefol** [grunwaldlab/poppr#220]
- [ x] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [ ] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [x ] I want to request a new feature

--------

Use case: 
- Comparing one individual to a set of individuals to incrementally update a distance matrix.
- Doing one off comparisons in order to find the closest match to n individuals in a reference set. IE search. 

Invocation could look something like
```r
bruvos_distance_between(bruvomat, query, funk_call = match.call(), add = TRUE, loss = TRUE, by_locus = FALSE)
```

And would return an abbreviated distance matrix that only includes the entries present in `query`.

I don't mind implementing this myself if there is the desire to make this happen but not enough bandwidth amongst the 
maintainers. 

---------

**Comment by zkamvar** [comment]
Just popping in here to confirm that I saw this, but it's the end of my day and I'm a bit doughy, so I'll come back to this sometime over the weekend. 

If I'm interpreting this correctly, this would allow someone to take a set of N samples and compare them to a reference database without performing the comparisons within the reference database?

**Comment by davefol** [comment]
Exactly

**Comment by zkamvar** [comment]
I'm all for it! I don't have the bandwidth to implement this myself, but if you are willing to submit a PR, I can definitely support that. I have a couple of followup questions:

1. Would you be okay being added as an author "[aut]" when you contribute? I feel it would be appropriate since you are contributing a new function (I really should add this to the [CONTRIBUTING](https://github.com/grunwaldlab/poppr/blob/main/CONTRIBUTING.md#contributing-new-code) section on new code)
2. Would you be okay with a different name for the exported function? I know poppr's style is a bit all over the place, but the Bruvo functions all have a consistent `bruvo.{thing}()` convention. Would you be okay with `bruvo.between()` or `bruvo.reference()`
3. Are you planning on implementing this in R or C? 

Other than that, this is a fantastic idea and I think it could also be implemented for other distances in the future. I am excited to see what you come up with. Thank you for the query!

**Comment by davefol** [comment]
Sure I don't mind putting together a PR. 

1. I'm fine with being added as an author. 
2. Hmm. both sound good although I think I prefer `bruvo.between()` I guess if you come up with something better you can change it on merge. 
3. I assumed R since I haven't poked around the C internals much but if you think its a good idea and you can point me to the C src I might take a crack at it. To be honest I haven't programmed much R since college (not that long ago!) so if the C implementation would be more straight forward that might be a good idea. As it is now, I'll start doing it in R though. 

Thanks for being so open to community requests and for being so responsive.

**Comment by zkamvar** [comment]
>  I assumed R since I haven't poked around the C internals much but if you think its a good idea and you can point me to the C src I might take a crack at it. To be honest I haven't programmed much R since college (not that long ago!) so if the C implementation would be more straight forward that might be a good idea. As it is now, I'll start doing it in R though.

Sounds good to me. The current path to calculate Bruvo's distance is this:

1. [`poppr::bruvo.dist()`](https://github.com/grunwaldlab/poppr/blob/9c797d5dd68b80f18c3309469c9c0b7ea5d8d277/R/bruvo.r#L215) converts the genind object to a [bruvomat S4 object](https://github.com/grunwaldlab/poppr/blob/9c797d5dd68b80f18c3309469c9c0b7ea5d8d277/R/classes.r#L148-L181) (which is an N x M matrix where N is the number of samples and M is the number of loci multiplied by the ploidy, such that each column represents an allele)
2. [`poppr:::bruvos_distance()`](https://github.com/grunwaldlab/poppr/blob/9c797d5dd68b80f18c3309469c9c0b7ea5d8d277/R/internal.r#L802-L803) divides the alleles by the repeat lengths, sends the params to C, and post-processes the output
3. [`SEXP bruvo_distance()` (C-level)](https://github.com/grunwaldlab/poppr/blob/9c797d5dd68b80f18c3309469c9c0b7ea5d8d277/src/poppr_distance.c#L325) takes the matrix of integers, loops through the pairs of individuals, and sends them to `bruvo_dist`
4. [`double bruvo_dist()` (C-level)](https://github.com/grunwaldlab/poppr/blob/9c797d5dd68b80f18c3309469c9c0b7ea5d8d277/src/poppr_distance.c#L474) takes in a 2 x M matrix and returns a double (and unfortunately the docs and function have gone out of sync, which is what you get with code that is over 5 years old 😞)

If you decide to work in the C-level, you will likely be interfacing with 4, `double bruvo_dist` through your own SEXP function, but if you work at the R-level, you would probably be passing data on to 3, `SEXP bruvo_distance()` via `.Call()`.

(Sorry about the names being all over the place)

Just give me a shout if you need me. Best of luck :)
