### ISSUE TITLE
Genetic distance calculation yields NAs

### ISSUE THREAD

**Issue by elizeng** [grunwaldlab/poppr#225]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [X] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

I am trying to calculate genetic distance using `rogers.dist`

The string of code I use is:

```
library(xlsx)
library("poppr")
MROB_gp <- read.genepop("MROB_genepop.gen", ncode = 3)
MROB_gen_dist<- rogers.dist(MROB_gp)
MROB_gen_dist_mat<-as.matrix(MROB_gen_dist)

write.xlsx(MROB_gen_dist_mat, "MROB_gd.xlsx")

```

trangely this code works for my other datasets, whereas for the dataset above which is by far the largest at 34,710 loci, the output I get is just a string of `NAs`

I do not think its an issue with the input file as it was generated exactly the same way as that of the others, but I am not sure why this particular dataset is generating `NAs`

I am attaching the text version of the genepop file for testing.. as github doesn't allow the upload of the .gen file.

[MROB_genepop2.txt](https://github.com/grunwaldlab/poppr/files/4992516/MROB_genepop2.txt)

---------

**Comment by zkamvar** [comment]
Hello,

It could be that you have missing data in all of your samples. Roger's distance cannot handle missing data. That's why you are getting all NAs. You might consider removing loci that have missing data with `missingno()`

**Comment by zkamvar** [comment]
I am closing this issue as resolved and stale. Please open with new information if it was not resolved.
