### ISSUE TITLE
Interpretation of negative values in AMOVA

### ISSUE THREAD

**Issue by GrimPerez** [grunwaldlab/poppr#229]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [x] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Please include a brief description of the problem with a code example:

```r
# insert reprex here
```
With all due respect I ask the following.

I carried out AMOVA based on STRUCTURE clustering and got the following results for % variance

Among populations                                     13%
Among individuals within populations      -11%
Within individuals                                        98%
Total                                                              100%

•What does the negative value in 'Among individuals within populations' (-11%) say?
•If the variation among populations (STRUCTURE clusters) is 13 percent, then how to calculate the variation within populations? -11% + 98% =87%  Or do I need to carry out some other calculation?

Sincerely,
Grim

---------

**Comment by zkamvar** [comment]
This is answered in the poppr forum: https://groups.google.com/g/poppr/c/NSag-55d6bs/m/PasHn3C7AQAJ

The "Among individuals within populations" is the variation within populations, you don't need to do a separate calculation.

**Comment by GrimPerez** [comment]
Thank you very much for the reply.

Regarding the variation within populations, I saw some research articles report it like this
Article 1: 
"Analysis of molecular variance (AMOVA) identified 4% variance among and 96% variance within subpopulations"

<img width="401" alt="Article 1" src="https://user-images.githubusercontent.com/51880237/93409238-9c6cb280-f8c0-11ea-9ca4-876bbbcd8394.png">

Article 2: 
"The AMOVA on the landrace population vs. cultivar population showed a much greater variation within a population (67.36% + 17.08% = 84.44%) than among the populations (15.56%, p < 0.001)"

<img width="808" alt="Article 2" src="https://user-images.githubusercontent.com/51880237/93409300-d2119b80-f8c0-11ea-9af3-1f76e36d94e0.png">

It seems like they add the 'Among individuals within populations' and 'Within individuals' %. Can you please provide your input as to why they report it like this?


Sincerely,
Grim

**Comment by zkamvar** [comment]
I would suggest for you to post to [R-SIG-Genetics](https://stat.ethz.ch/mailman/listinfo/r-sig-genetics) about this inquiry because there are people on that list with much more expertise in AMOVA than I (poppr only provides an interface for two different amova functions in the ade4 and pegas packages). I'm afraid I cannot interpret single quotes and table images from random articles without citations or context.
