### ISSUE TITLE
Error with reverse dependency checks for phangorn

### ISSUE THREAD

**Issue by KlausVigo** [grunwaldlab/poppr#230]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [ ] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Hello all, 

I am trying to submit a new version of phangorn to CRAN and reverse dependency checks show a problem with `poppr`. Maybe  you guys probably can give me a hint why this happens, so that I can fix it. 

When checking poppr against the development version of R I get this error
```r
W  checking data for non-ASCII characters (3.7s)
     Error loading dataset 'Pinf':
      Error in .requirePackage(package) : 
       unable to find required package 'poppr'
     
     Error loading dataset 'Pram':
      Error in .requirePackage(package) : 
       unable to find required package 'poppr'
     
     Error loading dataset 'monpop':
      Error in .requirePackage(package) : 
       unable to find required package 'poppr'
     
     Error loading dataset 'old_Pinf':
      Error in .requirePackage(package) : 
       unable to find required package 'poppr'
     
     The dataset(s) may use package(s) not declared in Depends/Imports.
```
The version on CRAN shows no error. 

Any idea what could this cause?? How are these data sets generated?
Are there any transformations between data formats, maybe to or from phyDat happening?

Thanks in advance and have a nice holiday season, 
Klaus

---------

**Comment by zkamvar** [comment]
Hi Klaus,

I'm actually running into the same problem as I'm trying to submit a patch to CRAN for poppr itself, which makes me think it's a bug on their end.

**Comment by KlausVigo** [comment]
Hi Zhian, 
I agree with you. That bug looks just weird, why should poppr not available. And I can't see how phangorn, where you only use upgma or midpoint can cause a problem with some data sets. 
Keep me updated. 
Cheers, 
Klaus

**Comment by zkamvar** [comment]
Will do! If it's any consolation, you can reply-all to CRAN and let them know that poppr's failure is a false-positive and not related to phangorn. 

For what it's worth, this is the initial response I got from CRAN:

------------------------------

package poppr_2.8.7.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/poppr_2.8.7_20201218_135617/Windows/00check.log>
Status: 1 WARNING
Debian: <https://win-builder.r-project.org/incoming_pretest/poppr_2.8.7_20201218_135617/Debian/00check.log>
Status: OK
 
Last released version's CRAN status: OK: 12
See: <https://CRAN.R-project.org/web/checks/check_results_poppr.html>
 
CRAN Web: <https://cran.r-project.org/package=poppr>
 
Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.
 
More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/poppr_2.8.7_20201218_135617/>
The files will be removed after roughly 7 days.
 
*** Strong rev. depends ***: popprxl
 
Best regards,
CRAN teams' auto-check service


Flavor: r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: NA
  Maintainer: 'Zhian N. Kamvar <zkamvar@gmail.com>'

Flavor: r-devel-windows-ix86+x86_64
Check: data for non-ASCII characters, Result: NA
    Error loading dataset 'Pinf':
     Error in .requirePackage(package) : 
      unable to find required package 'poppr'
    
    Error loading dataset 'Pram':
     Error in .requirePackage(package) : 
      unable to find required package 'poppr'
    
    Error loading dataset 'monpop':
     Error in .requirePackage(package) : 
      unable to find required package 'poppr'
    
    Error loading dataset 'old_Pinf':
     Error in .requirePackage(package) : 
      unable to find required package 'poppr'
    
    The dataset(s) may use package(s) not declared in Depends/Imports.

Flavor: r-devel-windows-ix86+x86_64
Check: Overall checktime, Result: NOTE
  Overall checktime 12 min > 10 min

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Zhian N. Kamvar <zkamvar@gmail.com>'

**Comment by zkamvar** [comment]
However, I get the feeling we won't hear about this until January :(

**Comment by KlausVigo** [comment]
Yes, I just saw that they are closed until the 4th and 6th is also an holiday in Austria.

**Comment by KlausVigo** [comment]
Hi @zkamvar, 
I see poppr is now on CRAN. Did you make any changes to get rid of the note or was it a problem on the CRAN site?

**Comment by zkamvar** [comment]
Hi @KlausVigo,

It was an error on CRAN's side. 

I never made any substantial code changes to poppr; only documentation. You can see that all the changes were for documentation: https://github.com/grunwaldlab/poppr/compare/v.2.8.6...cran-patch-docs

**Comment by zkamvar** [comment]
Hi @KlausVigo,

Do you still see these issues or can I close this?

**Comment by KlausVigo** [comment]
Hi @zkamvar, 
I still see this issue. While it does not fix the issue the pull request #237 makes poppr not to depend from phangorn. There is only one function imported upgma. midpont is imported, but not used inside poppr. upgma is a one-liner, just calling hclust and transforming the resulting tree to a phylo object. 
Cheers,  Klaus

**Comment by zkamvar** [comment]
I'm surprised that it's still coming up as an issue since it's no longer appearing on my end. 

I'll merge #237 and submit it next week since I just submitted a major update this week and they will likely be grumpy about it.

**Comment by KlausVigo** [comment]
Thanks a lot @zkamvar, 
Uwe Ligges was also puzzled from this error and phangorn is still sitting in the loop on CRAN.

**Comment by zkamvar** [comment]
Thank you for your patience with this @KlausVigo. I apologize for the large amount of time it took to get this pushed; the winter has not been kind to my mental health.
