### ISSUE TITLE
Error in bruvo.boot

### ISSUE THREAD

**Issue by zhangqingah** [grunwaldlab/poppr#240]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of poppr and R
 - [x] I have found a bug
   - [x] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [x] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------
I am trying to calculate the bootstrap values using bruvo.boot.
Here is the code i used:

```r
geno_genind <- df2genind(geno_sample, ploidy='2', sep = '/', type = 'codom')
geno_genind <- missingno(geno_genind, type = 'mean', quiet = FALSE, freq = FALSE)
tree<-bruvo.boot(geno_genind, replen = 1, sample=500, tree='upgma',showtree=F)
tree<-bruvo.boot(geno_genind, replen = 1, sample=500, tree='fastme.bal',showtree=F)
tree<-bruvo.boot(geno_genind, replen = 1, sample=500, tree='nj',showtree=F)
```

I got error message , when "tree = nj" was used:

```
Error in treefun(bruvos_distance(x, funk_call = match.call(), add = add,  :
  missing values are not allowed in the distance matrix
Consider using njs()
Calls: bruvo.boot -> boot.phylo -> FUN -> treefun
```

and got error message, when "tree = upgma" was used:

```
Error in hclust(DD, method = method, ...) :
 NA/NaN/Inf in foreign function call (arg 11)
Calls: bruvo.boot -> boot.phylo -> FUN -> treefun -> hclust
```

Confusingly, when i run the code below, no error was reported:
dist <- bruvo.dist(geno_genind)
nj(dist)

Most curious of all, when i accidently deleted the first two samples, which have no missing value, no error returned!

I attach the text file of 'geno_sample' for testing. Appreciating your contribution, and look forward to your reply!

[geno_sample.txt](https://github.com/grunwaldlab/poppr/files/6371926/geno_sample.txt)

**Comment by zkamvar** [comment]
I have three suggestions for you:

1. DO NOT use missingno() with type = "mean" on your data (I will update the documentaiton for this, it originates from back when adegenet internally represented data with floats)
2. specify the repeat lengths of your alleles. If your data already represents the alleles, you can use `replen = rep(1L, nLoc(geno_genind)`
3. Use `njs()` from the ape package. Sample H46 has just barely enough data to create a tree, but the two loci it provides fall out in some of the randomizations, causing the error in the tree functions. `njs()` can help overcome that. 

There are definitely a few things going on, but primarily: you should never use missing data correction with Bruvo's distance: https://grunwaldlab.github.io/poppr/reference/bruvo.dist.html#note
 
When you corrected your data with "mean", even though you tried to use `freq = FALSE`, it still gave you frequencies (this is something I need to fix in the documentation). Bruvo's distance starts by transforming the count matrix back into numeric representations of the data via `genind2df()`, however, when you do that on the "missing-corrected" data above, you end up with a table of genotypes similar to what you started with: 

```
     F3   F4 F13  F6  F8    F5  F14  F9  F7  F15 F10  F1 F11 F12  F2
H01 6/6  5/6 4/5 5/5 2/2 10/10  5/5 3/3 7/7  6/6 2/3 2/2 3/3 4/4 1/2
H02 1/5  1/1 3/3 2/2 3/3   6/6  1/4 1/1 5/5  3/9 2/3 3/8 3/2 4/4 2/2
H03 6/5  1/3 4/3 2/2 4/4   6/6  4/4 1/1 5/5  9/9 3/3 3/3 3/2 4/2 2/5
H04 6/1  1/3 3/3 2/2 4/4   6/6  4/4 3/3 5/5  6/9 3/3 3/3 2/2 4/2 2/5
H05 5/5  6/3 4/5 5/5 4/5  10/6  5/6 3/3 5/3  2/7 2/3     3/3 2/3 2/2
H06 1/5  6/1 4/3 5/5 4/5 10/10  5/4 3/2 3/4  6/2 2/3 3/8 3/3 3/1 2/3
H07 1/2  1/8 3/6 4/4 3/4   6/6  6/6 3/5 5/3  3/3 2/2 3/7 3/3 2/1 1/2
H08 1/5  1/1 3/3 2/2 3/3   6/6  1/4 1/1 5/5  3/9 2/3 3/8 3/2 4/4 2/2
H09 1/1  5/6 4/3 5/3 4/5  10/8  5/5 2/2 3/1  2/8 3/1 2/3 3/3 4/4 1/1
H10 1/2  3/8 4/5 4/4 4/5  6/11  1/1 3/4 5/5  6/6 2/2 3/7 3/3 1/1 2/2
H40 1/1  6/8 5/3 2/3 2/2  11/4  1/2 3/3 5/6  6/2 2/2 3/3 3/3 1/5 1/2
H41 6/1  1/3 3/3 4/4 3/4   6/6  1/2 1/5 5/5  6/6 2/3 3/7 3/3 2/2 2/2
H42 6/1  1/3 3/3 4/4 3/4   6/6  1/2 1/5 5/5  6/6 2/3 3/7 3/3 2/2 2/2
H43 1/4  3/7 4/4 5/1 3/3  9/12  6/6 5/5 1/2  6/6 2/3     3/3 2/3 2/4
H44 1/5  3/8 3/6 2/2 4/4   6/5  4/6 1/5 5/1  6/9 2/3 3/7 3/2 4/2 2/2
H45 1/5  1/3 5/3 4/4 3/5  11/7  1/6 3/4 5/1  6/6 2/2 7/6 3/3 4/1 2/2
H46      6/9   3             6            5      2/3       3       2
H47 2/4  1/3 5/3 5/2 4/5  12/7  1/1 3/1 5/1  6/4 2/2 7/7 3/2 1/1 2/3
H48 6/1  1/1 4/3 5/5 4/4   6/6  4/6 3/1 5/1  6/8 3/3 3/8 2/2 2/1 2/2
H11 2/2  1/1 3/6 3/3 4/5   6/6  1/1 3/5 5/1  6/3 2/2 8/7 3/3 1/1 2/2
H12 2/4  1/8 5/3 2/2 4/5   6/6  1/1 5/5 5/4  3/4 2/2 8/7 3/3 2/2 2/5
H13 5/5  1/8 5/3 4/4 2/5   6/6  1/6 3/4 5/5  6/7 2/2 7/6 3/3 4/1 2/3
H14 1/4  3/8 3/6 2/4 4/5  6/11  1/6 3/5 5/1  6/6 2/2 7/7 3/2 4/2 2/7
H15 5/5  1/1 3/3 5/5 2/2 10/10  4/6 3/1 5/1  6/6 2/3 3/6 3/2 4/4 2/5
H16 2/4  1/3 4/3 3/3 4/4 10/10  6/6 5/4 5/5  6/9 2/2 3/3 3/3 4/1 2/3
H17 1/2  1/8 3/6 4/4 3/4   6/6  6/6 3/5 5/3  3/3 2/2 3/7 3/3 2/1 1/2
H18 1/2  1/3 4/3 5/5 4/4  10/6  1/4 3/2 5/4  6/6 3/3 3/3 3/2 4/2 1/1
H19 1/2  1/8 4/6 2/4 4/4   6/6  1/6 3/4 5/1  3/4 2/2 7/7 3/2 4/2 2/2
H20 6/5  1/3 3/3 2/2 1/1   6/4  4/4 3/1 5/4 1/11 3/3 3/1 3/2 2/1 2/8
H50 5/5 1/11 3/1 2/2 3/3   6/1 4/10 1/1 5/5  3/3 3/4 3/4 3/1 1/1 2/4
H51 7/7 6/10 5/2 3/3 1/6   6/3  2/9 2/2 3/3  6/6 3/5 3/5 3/1 4/1 2/5
H52 7/7 6/10 5/2 3/3 1/6   6/3  2/9 2/2 3/3  6/6 3/5 3/5 3/1 4/1 2/5
H53 6/2  3/8 3/3 3/3 4/4   6/6  4/6 3/1 5/5  9/9 2/3 3/3 3/2 4/1 2/2
H54 5/5  1/1 3/3 5/5 3/4   6/6  4/4 1/1 5/4  6/9 3/3 3/3 3/2 4/1 2/4
H55 1/4  1/8 3/6 1/1 4/4   7/1  7/7 2/2 5/3  9/9 2/3 3/6 3/3 1/1 2/5
H56 1/1  3/2 4/6 5/5 4/4   6/6  6/6 3/3 5/3  3/3 2/2 6/6 3/3 4/4 1/2
H57 2/2  1/3 4/6 2/4 3/4   6/6  1/6 3/2 5/1  6/3 2/3 3/7 3/3 1/1 2/2
H58 6/3  6/1 3/3 5/2 3/5   4/5  5/4 3/1 5/3 6/10 3/3     3/3 4/2 1/2
```

The reason WHY this happens is because `genind2df()` assumes that the incoming data are integers to repeat the alleles by their counts, but if you try to repeat something by a float, R will take the floor to repeat, meaning that a lot of the alleles will be lost.

**Comment by zhangqingah** [comment]
Thank you so much for your reply and advice.  It really helps. Instead of correcting the data with "mean", I removed loci and samples that have missing data with missingno(). In this example, i use the following code :
geno_genind <- missingno(geno_genind, type = 'loci', cutoff = 0.1, quiet = FALSE, freq = FALSE)
geno_genind <- missingno(geno_genind, type = 'geno', cutoff = 0.8, quiet = FALSE, freq = FALSE)

I am wondering if there is a recommended cutoff to filter the data.

**Comment by zkamvar** [comment]
> Thank you so much for your reply and advice. It really helps. Instead of correcting the data with "mean", I removed loci and samples that have missing data with missingno(). In this example, i use the following code :
> geno_genind <- missingno(geno_genind, type = 'loci', cutoff = 0.1, quiet = FALSE, freq = FALSE)
> geno_genind <- missingno(geno_genind, type = 'geno', cutoff = 0.8, quiet = FALSE, freq = FALSE)
> 
> I am wondering if there is a recommended cutoff to filter the data.

To be honest, I don't think you should need to remove loci at all for this data set. Bruvo's distance will handle it since you have most of the loci typed. Your main problem is sample H46 since it's only typed at two loci. Removing that sample or using njs() should be sufficient.

**Comment by zkamvar** [comment]
I will close this issue as I believe it has been resolved. If you think this is a mistake, feel free to reopen it.
