### ISSUE TITLE
 Preserve state of random number generator in .onAttach()

### ISSUE THREAD

**Issue by TimTaylor** [grunwaldlab/poppr#259]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of poppr and R
 - [x] I have found a bug
   - [ ] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [x] I want to request a new feature

--------

Currently .onAttach() will change the state of a users random number generator.

https://github.com/grunwaldlab/poppr/blob/2ae5741bb73b4034993dc6c58ec264c379fbd6f5/R/zzz.r#L57 

Not a bug per se but would you consider a change to preserve it?

For reference I believe {ggplot2} was updated to use withr::with_preserve_seed() for this reason.

Motivate by this thread https://fosstodon.org/@henrikbengtsson@mastodon.social/112079393660379008

---------

**Comment by zkamvar** [comment]
Thank you for opening this, Tim. I think a change should definitely happen. I'll probably use Ben's millisecond trick to avoid calling the rng all together.

**Comment by zkamvar** [comment]
Alas, the RNG is still modified, which means that one of the packages being loaded is modifying it. I tried debugging for set.seed(), but that gave me shiny, which should safely modify its own internal seed.

**Comment by zkamvar** [comment]
Actually, shiny might be the culprit here.

``` r
exists(".Random.seed")
#> [1] FALSE
library(shiny)
exists(".Random.seed")
#> [1] TRUE
```

<sup>Created on 2024-03-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by zkamvar** [comment]
Ah yeah that does make sense! Thank you!
