### ISSUE TITLE
Ensure that bitwise.IA works for diploids

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#31]

**Comment by JonahBrooks** [comment]
I've fixed a plethora of small bugs and issues with the diploid version of bitwise.IA. It now produces values fairly close to the existing win.ia code. Unfortunately the output is still not exactly the same, and occasionally spikes upwards of 20% relative error (although it averages much better than that). It seems something is wrong with the accumulation of distance at each locus (M[] and M2[]). Everything else is matching up to win.IA exactly.

Right now I can generate the following output from both functions while running ia_comparison. Each time the values shown are computed they are written to a file. This is the diff between (the first few differences in) those two output files ( > represents bitwise.IA output, < represents snpia):

```
2,5c2,5
< Sd*Sd/np:1543.372929
< Sd2:3384
< vars:0.371844
<  
---
> Sd*Sd/np:1722.505051
> Sd2:3664
> vars:0.392221
> 
9,21c9,21
<  
< Sd*Sd/np:986.686869
< Sd2:2210
< vars:0.247134
<  
< Sd*Sd/np:2673.746263
< Sd2:4982
< vars:0.466314
<  
< Sd*Sd/np:1355.171717
< Sd2:3110
< vars:0.354511
<  
---
> 
> Sd*Sd/np:1138.560808
> Sd2:2504
> vars:0.275846
> 
> Sd*Sd/np:2872.816364
> Sd2:5211
> vars:0.472360
> 
> Sd*Sd/np:1527.777778
> Sd2:3400
> vars:0.378227
> 
29,37c29,37
<  
< Sd*Sd/np:1813.336566
< Sd2:4004
< vars:0.442558
<  
< Sd*Sd/np:1961.506263
< Sd2:4480
< vars:0.508787
<  
---
> 
> Sd*Sd/np:2004.545455
> Sd2:4284
> vars:0.460496
> 
> Sd*Sd/np:2560.323232
> Sd2:5296
> vars:0.552662
> 
41,45c41,45
<  
< Sd*Sd/np:1397.353535
< Sd2:3250
< vars:0.374272
<  
---
> 
> Sd*Sd/np:1931.406869
> Sd2:4084
> vars:0.434867
> 
49,53c49,53
<  
< Sd*Sd/np:983.118384
< Sd2:2342
< vars:0.274522
<  
---
> 
> Sd*Sd/np:1136.643232
> Sd2:2644
> vars:0.304517
> 
```

**Comment by JonahBrooks** [comment]
Commit c4059d2d4fe56e8b89668cdb5fa165c01df9eb77 resolves the issues and completes this functionality. bitwise.IA should now correctly support diploids.
