### ISSUE TITLE
ensure bitwise.IA can handle missing data.

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#33]

**Comment by JonahBrooks** [comment]
bitwise.IA is still not quite functional, but commit f5dfb05a8f738dd5b7383d95fb187c55547587e1 added support for missing data. I'll leave this open until I get the rest of the bugs worked out so I can test the missing data handler.

**Comment by JonahBrooks** [comment]
Commit ffffaca3ab1f4942aa0395e2d2f5906a6a0114b7 added haploid support, including missing data handling. bitwise.IA should now be able to handle missing data for both haploid and diploid data sets.
