### ISSUE TITLE
Allow for named color vector input for msn functions

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#55]
Currently the msn functions only allow palettes to be input. This becomes burdensome when the user wants specific colors for the nodes and has to input the palette such as `function(x) myPalette`

**Comment by zkamvar** [comment]
Why did you reopen this? This issue was fixed in #57.

**Comment by knausb** [comment]
Documentation states that the function `poppr.msn()` will accept a vector of colors. I may have found an exception.

    A.dist <- diss.dist(Aeut)
    A.msn <- poppr.msn(Aeut, A.dist, gadj=15, vertex.label=NA)

From examples works.

    RColorBrewer::brewer.pal(n=3, name = 'Set3')
    A.msn <- poppr.msn(Aeut, A.dist, gadj=15, vertex.label=NA, palette=RColorBrewer::brewer.pal(n=3, name = 'Set3'))

Throws an error. 

    Error in PAL(npop) : invalid argument type

Is poppr.msn trying to interpret this as a function instead of a vector of colors?

Thanks!

**Comment by zkamvar** [comment]
That's an interesting problem. The function responsible for figuring out if a palette is a vector or function is [`palette_parser`](https://github.com/grunwaldlab/poppr/blob/db7094a5585212ab8b0363088dcefe8f1a25e89f/R/internal.r#L1849 <https://github.com/grunwaldlab/poppr/blob/db7094a5585212ab8b0363088dcefe8f1a25e89f/R/internal.r#L1849>). It's strange that it would throw that error. In fact, it should throw a warning.

I'll have a look at this later.

Zhian

**Comment by zkamvar** [comment]
This has been fixed. There was something weird with `match.fun()`, but setting `descend = FALSE` did the trick. I also added a new feature that would give you what I'd hope you'd expect.

For future reference, if you find a bug that stemmed from a new feature, please raise a separate issue; it makes things easier to track down.
