### ISSUE TITLE
poppr_manual

### ISSUE THREAD

**Issue by juance100** [grunwaldlab/poppr#64]
The trick suggested in page 18 of poppr_manual (Data import and manipulation) to assign a geographic coordinate to each individual when exporting the nancycats object to GenAlex does not take into account that individuals in nancycats are not ordered by population. My suggestion is using the following script

```r
nan2 <- nancycats
other(nan2)$xy <- matrix(nrow=237, ncol=2) 
for(i in 1:237) {
  nan2$other$xy[i, 1:2] <- nancycats$other$xy[row.names(nancycats$other$xy)==pop(nancycats)[i]]
}
dimnames(nan2$other$xy) <- list(row.names(tab(nancycats)), c("x","y"))
genind2genalex(nan2,"nancycats_inds_xy.csv",geo=TRUE)
```

**Comment by zkamvar** [comment]
This is a good point!  A more elegant solution would be:
```r
other(nancycats)$xy <- other(nancycats)$xy[pop(nancycats), ]
```
since the rows are named.

I will correct this and send it to CRAN on the next version. Thanks!

**Comment by juance100** [comment]
That's a simple and good solution.
