### ISSUE TITLE
Manual can be compressed

### ISSUE THREAD

**Issue by KlausVigo** [grunwaldlab/poppr#73]
Hi @zkamvar, 

just checked reverse dependencies of phangorn and it came up with a warning for poppr (was probably an older version, but has similar file size on github):
```
checking sizes of PDF files under ‘inst/doc’ ... WARNING
  ‘gs+qpdf’ made some significant size reductions:
     compacted ‘poppr_manual.pdf’ from 800Kb to 541Kb
  consider running tools::compactPDF(gs_quality = "ebook") on these files
```
May want to consider doing this when preparing a new release. 

Cheers,
Klaus

PS: checking reverse dependencies is a nightmare. Had to downgrade packages to upgrade bioconductor.

**Comment by zkamvar** [comment]
Thanks for the heads up, Klaus. I actually do have the compression set to gs+qpdf, so it's all good :smile: : https://github.com/grunwaldlab/poppr/blob/master/poppr.Rproj#L17

Zhian
