### ISSUE TITLE
poppr() error: no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by knausb** [grunwaldlab/poppr#82]
The function poppr() throws an error when I try to call it with a snpclone object. Should this work?

    devtools::install_github(repo = "grunwaldlab/poppr@devel", build_vignettes = TRUE)
    library("poppr")
    library(vcfR)
    vcf_file <- system.file("extdata", "pinf_sc50.vcf.gz", package = "pinfsc50")
    vcf <- read.vcfR(vcf_file, verbose = FALSE)
    x <- vcfR2genlight(vcf)
    x <- as.snpclone(x)
    poppr(x)
    Error in as.character.default(char) : 
      no method for coercing this S4 class to a vector

Thank you!

**Comment by zkamvar** [comment]
This is normal. The poppr function does not work for genlight objects. What is the desired outcome?

**Comment by knausb** [comment]
I was hoping to get a poppr summary table. If the poppr function does not work on genlight objects then we'll have to call this user error.

**Comment by zkamvar** [comment]
What information do you want from the table? If you want MLG diversity, use diversity_table(). The index of association is available as win.ia() and samp.ia()
