### ISSUE TITLE
newline needed for snpclone show method?

### ISSUE THREAD

**Issue by knausb** [grunwaldlab/poppr#83]
When I use R from the Unix terminal and use the show method for a snpclone object it seems to be misssing a newline at the end.

    > x
     /// GENLIGHT OBJECT /////////

     // 18 genotypes,  21,719 binary SNPs, size: 589.9 Kb
     31239 (7.99 %) missing data

     // Basic content
       @gen: list of 18 SNPbin
       @ploidy: ploidy of each individual  (range: 2-2)

     // Optional content
       @ind.names:  18 individual labels
       @loc.names:  21719 locus labels
       @chromosome: factor storing chromosomes of the SNPs
       @position: integer storing positions of the SNPs
       @other: a list containing: elements without names 

     // snpclone contents ---
       @mlg: 18 original multilocus genotypes> 

This does not appear to be an issue when using RStudio, just when using the terminal.

Thanks!

**Comment by zkamvar** [comment]
Will Fix. Thanks for the report.
